// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHtAho51gYGZaPqZFaPG_-Zyk5JzVLLeE',
    appId: '1:761518283691:ios:0aae93820f0035951d10ee',
    messagingSenderId: '761518283691',
    projectId: 'obpark-d6645',
    storageBucket: 'obpark-d6645.firebasestorage.app',
    iosBundleId: 'com.example.obPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHtAho51gYGZaPqZFaPG_-Zyk5JzVLLeE',
    appId: '1:761518283691:ios:0aae93820f0035951d10ee',
    messagingSenderId: '761518283691',
    projectId: 'obpark-d6645',
    storageBucket: 'obpark-d6645.firebasestorage.app',
    iosBundleId: 'com.example.obPark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4wrdGNaKBU2wejyGJhHoaEG5TIcmIMvM',
    appId: '1:761518283691:web:0ce84014cf3bfc961d10ee',
    messagingSenderId: '761518283691',
    projectId: 'obpark-d6645',
    authDomain: 'obpark-d6645.firebaseapp.com',
    storageBucket: 'obpark-d6645.firebasestorage.app',
    measurementId: 'G-805Z8BWNYN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wrdGNaKBU2wejyGJhHoaEG5TIcmIMvM',
    appId: '1:761518283691:web:0ce84014cf3bfc961d10ee',
    messagingSenderId: '761518283691',
    projectId: 'obpark-d6645',
    authDomain: 'obpark-d6645.firebaseapp.com',
    storageBucket: 'obpark-d6645.firebasestorage.app',
    measurementId: 'G-805Z8BWNYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkWMVS1nF_VHq2X-e6BRZlOQDU3etKjHY',
    appId: '1:761518283691:android:b8c34dead7fbdc8d1d10ee',
    messagingSenderId: '761518283691',
    projectId: 'obpark-d6645',
    storageBucket: 'obpark-d6645.firebasestorage.app',
  );

}